### ISSUE TITLE
Notebook tutorial

### ISSUE THREAD

**Issue by alexandreCameron** [LiyuanLucasLiu/RAdam#16]
I'm trying to find the easiest way to test RAdam.

Could you commit a basic jupyter notebook to test MNIST for instance ?

**Comment by find1dream** [comment]
```python
import radam
optimizer = radam.RAdam(net.parameters())
```

**Comment by AmithAdiraju16** [comment]
@LiyuanLucasLiu  Great Paper ! We'd be grateful if you could also share how to install this module using pip, I think that information is not too obvious from the documentation. Thanks !

**Comment by heartInsert** [comment]
> @LiyuanLucasLiu Great Paper ! We'd be grateful if you could also share how to install this module using pip, I think that information is not too obvious from the documentation. Thanks !

You  just need to  copy   radam.py    into   your  project   ,  why  do  you  want  to install  it  by  pip?

**Comment by pabloppp** [comment]
I created a small repo where I added this and other optimizers (and other tools) https://github.com/pabloppp/pytorch-tools
It's mainly **for personal use** so expect things braking and changing a lot, and also probably not being updated at the same peace as this or other original repositories, but you can install it with pip by doing
```
pip install git+https://github.com/pabloppp/pytorch-tools
```
I haven't published to the PyPi repo because, as I said it's for personal use, but I made it installable with pip so I can easily use it everywhere by just running the above line.

Then you have access to this and other optimizers by just doing
```python
from torchtools.optim import RAdam
optimizer = RAdam(model.parameters()) 
```

Again, I want to be very clear that the repo is mainly **for personal use**, so don't rely too much on it, but I'm trying to keep it updated with this and other repositories like this one: https://github.com/mgrankin/over9000

**Comment by AmithAdiraju16** [comment]
> > @LiyuanLucasLiu Great Paper ! We'd be grateful if you could also share how to install this module using pip, I think that information is not too obvious from the documentation. Thanks !
> 
> You just need to copy radam.py into your project , why do you want to install it by pip?

So that I don't have to carry around the source code :/

**Comment by AmithAdiraju16** [comment]
> I created a small repo where I added this and other optimizers (and other tools) https://github.com/pabloppp/pytorch-tools
> It's mainly **for personal use** so expect things braking and changing a lot, and also probably not being updated at the same peace as this or other original repositories, but you can install it with pip by doing
> 
> ```
> pip install git+https://github.com/pabloppp/pytorch-tools
> ```
> 
> I haven't published to the PyPi repo because, as I said it's for personal use, but I made it installable with pip so I can easily use it everywhere by just running the above line.
> 
> Then you have access to this and other optimizers by just doing
> 
> ```python
> from torchtools.optim import RAdam
> optimizer = RAdam(model.parameters()) 
> ```
> 
> Again, I want to be very clear that the repo is mainly **for personal use**, so don't rely too much on it, but I'm trying to keep it updated with this and other repositories like this one: https://github.com/mgrankin/over9000

Thanks for pointing me to this ! I will keep that in mind.

**Comment by LiyuanLucasLiu** [comment]
Thanks for the discussion : -)
