### ISSUE TITLE
distributed training generating "exp_avg error"

### ISSUE THREAD

**Issue by h-jia** [LiyuanLucasLiu/RAdam#27]
Hi, Thanks for sharing the code. I have test on the single node programming and it works.

However, when I use distributed training in Pytorch, it saids:

`line 39, in step`
`state['exp_avg'] = state['exp_avg'].type_as(p_data_fp32)`
`KeyError: 'exp_avg'`

Any suggestions towards this?

Much appreciated for any comments!

**Comment by LiyuanLucasLiu** [comment]
I would recommend to use packages like `ipdb` or `pdb` to debug, they are quite effective, especially their `set_trace` method. 

From my point of view, since I'm not quite familiar with the distributed training in PyTorch, I can only provide some random guesses. In the DataParallel, I remember that only the `buffer` and `parameter` will be duplicated and broadcasted. My guess could be maybe the `state` is not registered as a buffer?

**Comment by h-jia** [comment]
Thanks resolved by changing back to signal node.
