### ISSUE TITLE
Typo in paper

### ISSUE THREAD

**Issue by zzaebok** [LiyuanLucasLiu/RAdam#32]
Hi, I read your arxiv paper and found some typos in it.

1. In Equation 1
![image](https://user-images.githubusercontent.com/44357534/65816249-57291e00-e234-11e9-8c7b-9fc6328b8869.png)
gt should be gi.

2. In numerator of Equation 3
![image](https://user-images.githubusercontent.com/44357534/65816274-948dab80-e234-11e9-8eaf-2a9ff93e2ce2.png)
I calculated it by myself and I think it is Gamma((rho-1)/2) instead of Gamma(rho/2 -1).

3. In
![image](https://user-images.githubusercontent.com/44357534/65826297-31942700-e2bd-11e9-8709-a0051a7bc78c.png)
SMA numerator and denominator are upside down .

Let me know if I was wrong :)

Thank you for interesting paper.

**Comment by LiyuanLucasLiu** [comment]
Nice catch and thanks for bringing this up : -) We'll fix it in the next version.

**Comment by omiita** [comment]
I appreciate your wonderful work! Would you explain the question 3. a bit more? 
I have 2 questions.
The correct SMA should be as follows but **why can you say the DoF of Scaled inverse chi square is f(t, ß2)?**
<img width="401" alt="Screen Shot 2020-01-21 at 12 31 42 PM" src="https://user-images.githubusercontent.com/29161998/72773401-5a647180-3c4a-11ea-8541-87544f80359d.png">

And also **why did you use (t+1-i) instead of g^2 in the following equation?**
<img width="401" alt="Screen Shot 2020-01-21 at 12 40 39 PM" src="https://user-images.githubusercontent.com/29161998/72773692-45d4a900-3c4b-11ea-8f87-87cb31763b94.png">

Thank you in advance!
