### ISSUE TITLE
About the estimation of DoF

### ISSUE THREAD

**Issue by omiita** [LiyuanLucasLiu/RAdam#45]
I appreciate your wonderful work! 
I have 2 questions about the estimation of degree of freedom.
According to the question 3 of [this issue](https://github.com/LiyuanLucasLiu/RAdam/issues/32), the correct SMA should be as follows but **why can you say the DoF of Scaled inverse chi square is f(t, ß2)?**
<img width="401" alt="Screen Shot 2020-01-21 at 12 31 42 PM" src="https://user-images.githubusercontent.com/29161998/72773401-5a647180-3c4a-11ea-8541-87544f80359d.png">

And, in the same section of your paper, **why did you use (t+1-i) instead of g^2 in the following equation?**

<img width="600" alt="Screen Shot 2020-01-21 at 12 46 41 PM" src="https://user-images.githubusercontent.com/29161998/72773935-212d0100-3c4c-11ea-883c-a1255307fd53.png">

Thank you in advance!

**Comment by LiyuanLucasLiu** [comment]
Thanks for asking!

1. 
From Wikipedia, it says:
> The scaled inverse chi-squared distribution is the distribution for x = 1/s2, where s2 is a sample mean of the squares of ν independent normal random variables that have mean 0 and inverse variance 1/σ2 = τ2.

Since f(., .) is the estimated length of the SMA, we use it as an estimation of degree of freedom. 

2. 
Here, "center of mass" refers to the center of mass for the weight list. Simple moving average assigns the same weight (1) to every item, and EMA assigns \beta_2^{t-i} to (t+1-i)-th item. Therefore, we can calculate the center of mass as \frac{\sum_i w_i \cdot p_i} {\sum_i w_i}
